config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:edit, :index, :show]
  resources :users, only: [:edit, :index, :show]

  get "/homes/about" => "homes#about", as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/98ff3f26d9.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <a class="nav-link text-light"><% if user_signed_in? %></a>
            <li class="nav-item">
              <a class="nav-link text-light"><%= link_to "Home", user_path(current_user.id) %></a>
            </li>
            <li class="nav-item">
              <%= link_to "Users", users_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Books", books_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <a class="nav-link text-light"><%= link_to "Home", root_path %></a>
            </li>
            <li>
              <a class="nav-link text-light>"><%= link_to "About", about_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light"><%= link_to "Sign up", new_user_registration_path %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light"><%= link_to "Log in", new_user_session_path %></a>
            </li>
          <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>

  </body>
</html>